//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLevel
    {
        public ActivityLevel()
        {
            this.Members = new HashSet<Member>();
            this.Programs = new HashSet<Program>();
            this.Workouts = new HashSet<Workout>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<Program> Programs { get; set; }
        public virtual ICollection<Workout> Workouts { get; set; }
    }
}
