//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gift
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public int Points { get; set; }
        public int Quantity { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime AddDate { get; set; }
        public string Store { get; set; }
        public bool IsPremium { get; set; }
    }
}
