//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupChat
    {
        public int ID { get; set; }
        public int GroupID { get; set; }
        public int MemberID { get; set; }
        public string Message { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Member Member { get; set; }
    }
}
