//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//    這個程式碼是由範本產生。
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.GroupChats = new HashSet<GroupChat>();
        }
    
        public int ID { get; set; }
        public string GroupName { get; set; }
        public int StartWeight { get; set; }
        public int EndWeight { get; set; }
        public bool IsAlive { get; set; }
        public bool IsService { get; set; }
    
        public virtual ICollection<GroupChat> GroupChats { get; set; }
    }
}
