//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelCollection
    {
        public int ID { get; set; }
        public int GetPoints { get; set; }
        public System.DateTime GetPointsDateTime { get; set; }
        public string Name { get; set; }
    }
}
