//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int MemberID { get; set; }
        public string OrderNumber { get; set; }
        public string OrderTime { get; set; }
        public bool OrderStatus { get; set; }
        public string PaidTime { get; set; }
    }
}
