//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//     This code was generated from a template.
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int MemberID { get; set; }
        public string OrderNumber { get; set; }
        public string OrderTime { get; set; }
        public bool OrderStatus { get; set; }
        public string PaidTime { get; set; }
    }
}
