//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int ID { get; set; }
        public int MemberID { get; set; }
        public int GetPoints { get; set; }
        public System.DateTime GetPointsDateTime { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> ProgramID { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Program Program { get; set; }
        public virtual Status Status { get; set; }
    }
}
