//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
            this.LikedPosts = new HashSet<LikedPost>();
            this.PostImages = new HashSet<PostImage>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string ShortContent { get; set; }
        public string PostContent { get; set; }
        public int CategoryID { get; set; }
        public int ViewCount { get; set; }
        public Nullable<int> MemberID { get; set; }
        public System.DateTime AddDate { get; set; }
        public int LikeCount { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<LikedPost> LikedPosts { get; set; }
        public virtual Member Member { get; set; }
        public virtual PostCategory PostCategory { get; set; }
        public virtual ICollection<PostImage> PostImages { get; set; }
    }
}
