//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.Points = new HashSet<Point>();
        }
    
        public int ID { get; set; }
        public int MemberID { get; set; }
        public int StatusID { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int TargetWeight { get; set; }
        public int ActivityLevelID { get; set; }
        public int InitialWeight { get; set; }
        public Nullable<int> ResultWeight { get; set; }
    
        public virtual ActivityLevel ActivityLevel { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<Point> Points { get; set; }
        public virtual Status Status { get; set; }
    }
}
