//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Members = new HashSet<Member>();
            this.Points = new HashSet<Point>();
            this.Programs = new HashSet<Program>();
            this.TempCustomerMealOptions = new HashSet<TempCustomerMealOption>();
            this.WorkoutLogs = new HashSet<WorkoutLog>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<Point> Points { get; set; }
        public virtual ICollection<Program> Programs { get; set; }
        public virtual ICollection<TempCustomerMealOption> TempCustomerMealOptions { get; set; }
        public virtual ICollection<WorkoutLog> WorkoutLogs { get; set; }
    }
}
