//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCustomerMealOption
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public double Calories { get; set; }
        public string ImagePath { get; set; }
        public int StatusID { get; set; }
        public int MealOptionID { get; set; }
        public int MemberID { get; set; }
        public string EditTime { get; set; }
        public string Date { get; set; }
        public bool IsValid { get; set; }
        public int TimeOfDayID { get; set; }
        public double Portion { get; set; }
        public string UnitName { get; set; }
    
        public virtual MealOption MealOption { get; set; }
        public virtual Member Member { get; set; }
        public virtual Status Status { get; set; }
        public virtual TimesOfDay TimesOfDay { get; set; }
    }
}
