//------------------------------------------------------------------------------
// <auto-generated>
<<<<<<< HEAD
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
=======
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
>>>>>>> 7c942b47a39b86640a9aa5a9d41bfe6249e00d4b
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workout
    {
        public Workout()
        {
            this.WorkoutLogs = new HashSet<WorkoutLog>();
        }
    
        public int ID { get; set; }
        public int WorkoutCategoryID { get; set; }
        public string Name { get; set; }
        public double Calories { get; set; }
        public int ActivityLevelID { get; set; }
    
        public virtual ActivityLevel ActivityLevel { get; set; }
        public virtual WorkoutCategory WorkoutCategory { get; set; }
        public virtual ICollection<WorkoutLog> WorkoutLogs { get; set; }
    }
}
